language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.llvm-builds

script:
  - SHOULD_FAIL="$SHOULD_FAIL" CAPSTONE_SYS_JOB="$CAPSTONE_SYS_JOB" RUST_PROFILE="$RUST_PROFILE" CAPSTONE_SYS_FEATURES="$CAPSTONE_SYS_FEATURES" ./ci/test.sh

env:
  global:
    - CARGO_TARGET_DIR=/tmp/bindgen
  matrix:

    # Should pass
    - CAPSTONE_SYS_JOB="test"    RUST_PROFILE=debug      CAPSTONE_SYS_FEATURES=""
    - CAPSTONE_SYS_JOB="test"    RUST_PROFILE=release    CAPSTONE_SYS_FEATURES=""
    - CAPSTONE_SYS_JOB="test"    RUST_PROFILE=debug      CAPSTONE_SYS_FEATURES="use_bindgen"
